Repository Studio-Yandex-Practicum/Tabit, pull requests merged in 2025-04, with the labels that each got.

#259 Add functional Result Meeting(#241)
  alembic/versions/05_change_resultmeeting.py
  src/api/v1/endpoints/problem_meetings.py
  src/api/v1/validators/meeting_validators.py
  src/problems/constants.py
  src/problems/crud/meeting.py
  src/problems/models/enums.py
  src/problems/models/meeting_models.py
  src/problems/schemas/meeting.py
Labels: enhancement

#268 Feature/tabit management staff tests
  src/crud/crud_moderator.py
  src/features_v1/constants.py
  src/features_v1/tabit_admin_management/endpoints.py
  tests/conftest.py
  tests/constants.py
  tests/test_problem_feeds.py
  tests/test_tabit_management_staff.py
  tests/utils.py
Labels: enhancement, good first issue

#293 Bugfix/refactor compose and workflow files
  .env.example
  .github/workflows/build_and_push.yaml
  .github/workflows/pytest.yaml
  .github/workflows/ruff.yml
  .github/workflows/stage_deploy.yaml
  .gitignore
  infra/docker-compose.test-db.yaml
  infra/local/docker-compose.local.yaml
  infra/stage/docker-compose.stage.yaml
  infra/stage/stage.Dockerfile
  infra/stage/tabit.service
  pgadmin/servers.json
Labels: bug

#298 Bugfix CI/CD
  .dockerignore
  .env.example
  .github/pull_request_template.md
  config/constants/tests.py
  infra/docker-compose.test-db.yaml
  infra/local/docker-compose.local.yaml
  infra/stage/docker-compose.stage.yaml
  infra/stage/stage.Dockerfile
Labels: bug

#256 Feature/problems endpoints tests
  config/constants/tests.py
  poetry.lock
  src/utils/association_utils.py
  tests/conftest.py
  tests/test_problems.py
Labels: enhancement, good first issue
