Repository Studio-Yandex-Practicum/Tabit, pull requests merged in 2025-03, with the labels that each got.

#186 Feature/send email
  .env.example
  poetry.lock
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  src/api/v1/endpoints/company.py
  src/api/v1/endpoints/company_user.py
  src/api/v1/routers.py
  src/companies/schemas/company.py
  src/config.py
  src/constants.py
  src/utils/__init__.py
  src/utils/email_service/__init__.py
  src/utils/email_service/constants_email.py
  src/utils/email_service/email_schema.py
  src/utils/email_service/send_email.py
  templates/email_template.html
Labels: enhancement

#201 bugfix/problem_feeds
  src/api/v1/endpoints/problem_feeds.py
  src/api/v1/validators/problem_feeds_validators.py
  src/problems/crud/problem.py
  src/problems/crud/problems.py
Labels: bug

#200 Make mail settigs optional to fix CI/CD
  src/config.py
Labels: bug

#203 Bugfix/problem feeds comment validation
  src/api/v1/endpoints/problem_feeds.py
  src/api/v1/validators/__init__.py
  src/api/v1/validators/problem_feeds_validators.py
  src/problems/constants.py
Labels: bug

#189 Feature/task crud
  alembic/versions/01_structure_initiation_after_refactoring.py
  alembic/versions/06_add_transfer_counter_to_task_model.py
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  src/api/v1/endpoints/tasks.py
  src/problems/crud.py
  src/problems/crud/__init__.py
  src/problems/crud/task_crud.py
  src/problems/models/association_models.py
  src/problems/models/meeting_models.py
  src/problems/models/task_models.py
  src/problems/schemas/task.py
  src/users/models/models.py
Labels: enhancement

#206 LicenseTypeFactory and filling function were added. Also annotations …
  Makefile
  README.md
  fake_data_factories/base_user_factory.py
  fake_data_factories/company_factories.py
  fake_data_factories/company_user_factories.py
  fake_data_factories/constants.py
  fake_data_factories/department_factories.py
  fake_data_factories/fill_db.py
  fake_data_factories/license_type_factories.py
Labels: enhancement

#202 Feature/tabit management companies validators
  .github/workflows/pytest.yaml
  poetry.lock
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  src/api/v1/endpoints/tabit_management_companies.py
  src/api/v1/endpoints/tabit_management_licenses.py
  src/api/v1/utilities.py
  src/api/v1/validators/tabit_management_companies_validators.py
  src/companies/constants.py
  src/companies/crud/company.py
  src/companies/schemas/company.py
  src/companies/schemas/mixins.py
  src/companies/validators/company_validators.py
  src/config.py
  src/constants.py
  src/crud.py
  tests/conftest.py
  tests/constants.py
  tests/test_company_user_auth.py
  tests/test_tabit_admin_auth.py
  tests/test_tabit_management_company.py
  tests/test_tabit_management_licenses.py
Labels: enhancement

#211 исправил миграции и запуск приложения в контейнере локально и добавил…
  .env.example
  Makefile
  README.md
  alembic/versions/06_add_transfer_counter_to_task_model.py
  infra/local/docker-compose.local.yaml
Labels: bug

#208 Add ONBOARDING_README.md for new developers
  docs/ONBOARDING_README.md
Labels: documentation, enhancement

#209 Add authors
  pyproject.toml
Labels: documentation

#221 Cоздание единого файла миграций #218
  alembic/versions/01_initial_migration.py
  alembic/versions/02_add_unique_constraints.py
  alembic/versions/03_add_unique_constraint_to_license_name.py
  alembic/versions/04_add_rating_to_comment_and_user_comment_.py
  alembic/versions/05_the_company_s_connection_to_the_problem_.py
  alembic/versions/06_add_transfer_counter_to_task_model.py
Labels: enhancement

#204 Feature/task validation
  poetry.lock
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  src/api/v1/endpoints/tasks.py
  src/api/v1/validators/tasks_validators.py
  src/problems/constants.py
  src/problems/crud/task_crud.py
  src/problems/schemas/task.py
  src/problems/validators/task_validators.py
Labels: enhancement

#233 bugfix/endpoint_user_me
  Tabit.postman_collection.json
  src/api/v1/constants.py
  src/api/v1/endpoints/__init__.py
  src/api/v1/endpoints/company_user.py
  src/api/v1/endpoints/company_user_auth.py
  src/api/v1/routers.py
  src/users/schemas/user.py
  tests/constants.py
  tests/test_company_user_auth.py
  tests/test_tabit_admin_auth.py
  tests/test_tabit_management_company.py
Labels: bug

#232 Update README.md
  README.md
  docs/ONBOARDING_README.md
Labels: bug, documentation

#235 Рефакторинг тестов, тестовая база теперь автоматически разворачивается в контейнере
  .env.example
  .github/workflows/pytest.yaml
  README.md
  infra/docker-compose.test-db.yaml
  poetry.lock
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  tests/conftest.py
  tests/constants.py
  tests/test_tabit_management_company.py
  tests/test_tabit_management_licenses.py
Labels: enhancement

#247 Add factories problem_factory and association_user_problem_factory
  fake_data_factories/association_user_problem_factory.py
  fake_data_factories/constants.py
  fake_data_factories/fill_db.py
  fake_data_factories/problem_factory.py
  poetry.lock
  requirements/dev.txt
Labels: enhancement, good first issue

#236 Добавлены тесты на эндпоинт /api/v1/auth/me
  poetry.lock
  pyproject.toml
  requirements/dev.txt
  requirements/prod.txt
  tests/constants.py
  tests/test_company_user_auth.py
  tests/test_tabit_management_company.py
Labels: enhancement

#243 Исправлены баги в GET и POST запросах к эндпоинтам promlems
  alembic/versions/01_initial_migration.py
  src/api/v1/endpoints/problems.py
  src/problems/crud/problems.py
  src/problems/models/association_models.py
  src/problems/models/problem_models.py
  src/problems/schemas/problem.py
Labels: bug

#207 Feature/problem feeds tests
  src/api/v1/endpoints/problem_feeds.py
  src/api/v1/validators/problem_feeds_validators.py
  tests/conftest.py
  tests/constants.py
  tests/test_problem_feeds.py
  tests/utils.py
Labels: enhancement

#250 Фабрика ленты сообщений
  Makefile
  README.md
  fake_data_factories/__init__.py
  fake_data_factories/association_user_problem_factory.py
  fake_data_factories/company_factories.py
  fake_data_factories/company_user_factories.py
  fake_data_factories/constants.py
  fake_data_factories/fill_db.py
  fake_data_factories/message_feed_factory.py
  fake_data_factories/problem_factory.py
  poetry.lock
  requirements/dev.txt
  requirements/prod.txt
Labels: enhancement

#264 Рефакторинг и добавление тестов для компании
  tests/conftest.py
  tests/constants.py
  tests/test_companies.py
  tests/test_problem_feeds.py
  tests/test_problem_meetings.py
  tests/test_tabit_management_company.py
Labels: enhancement

#266 Фабрика вариантов голосования
  Makefile
  README.md
  fake_data_factories/__init__.py
  fake_data_factories/constants.py
  fake_data_factories/fill_db.py
  fake_data_factories/voting_feed_factory.py
Labels: enhancement

#257 Bugfix/tabit management departments
  src/api/v1/endpoints/tabit_management.py
  src/api/v1/validators/__init__.py
  src/api/v1/validators/tabit_management_validators.py
  src/companies/constants.py
  src/tabit_management/crud/admin_user.py
  src/tabit_management/schemas/admin_company.py
Labels: bug

#261 Обработка ошибок при валидации по полю telegram_username в эндпойнтах company.py
  src/api/v1/endpoints/company.py
  src/api/v1/endpoints/company_user_auth.py
  src/api/v1/validators/__init__.py
  tests/test_companies.py
  tests/test_company_user_auth.py
Labels: bug

#263 Handling non-existent license ID errors (#255)
  src/api/v1/endpoints/tabit_management_companies.py
  tests/constants.py
  tests/test_tabit_management_company.py
Labels: bug

#260 fix_department
  alembic/versions/03_fix_department.py
  src/api/v1/endpoints/company.py
  src/api/v1/validators/company_validators.py
  src/companies/schemas/company.py
  src/constants.py
  src/users/models/models.py
  tests/constants.py
  tests/test_companies.py
Labels: bug

#248 Feature/infra refactor less compose add static
  .dockerignore
  .env.example
  .gitignore
  Makefile
  README.md
  alembic.ini
  infra/docker-compose.local-db.yaml
  infra/docker-compose.local-with-pgadmin.yaml
  infra/local/docker-compose.local.yaml
  infra/local/stage.Dockerfile
  infra/stage/docker-compose.stage.yaml
  infra/stage/stage.Dockerfile
  pgadmin/.pgpass.template
  pgadmin/create-admin-folder.sh
  src/config.py
  src/main.py
  tests/conftest.py
  tests/constants.py
Labels: enhancement

#272 Fix 03_migration for deploy
  alembic/versions/03_fix_department.py
Labels: bug

#273 Revert "Fix 03_migration for deploy"
  alembic/versions/03_fix_department.py
Labels: bug

#275 Feature/factory voting by user
  Makefile
  README.md
  fake_data_factories/fill_db.py
  fake_data_factories/voting_by_user_factory.py
  tests/test_tabit_management_company.py
Labels: enhancement

#269 Добавлены фабрики для TagUser, AssociationUserTags
  Makefile
  README.md
  fake_data_factories/__init__.py
  fake_data_factories/association_user_tags_factory.py
  fake_data_factories/constants.py
  fake_data_factories/fill_db.py
  fake_data_factories/tag_factories.py
  fake_data_factories/voting_by_user_factory.py
Labels: enhancement

#274 Feature/factories commentfeed
  Makefile
  README.md
  fake_data_factories/__init__.py
  fake_data_factories/association_user_comment_factory.py
  fake_data_factories/comment_feed_factory.py
  fake_data_factories/constants.py
  fake_data_factories/fill_db.py
  fake_data_factories/message_feed_factory.py
Labels: enhancement
